# Application name
spring.application.name=YEOGINAMGIM-BACKEND

# Import secret properties if exists
spring.config.import=optional:application-secret.properties

# Server port
server.port=8080

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.jdbc.bind = TRACE

# Data.sql settings
spring.sql.init.mode = never
spring.sql.init.data-locations=classpath:/sql/data.sql
spring.jpa.defer-datasource-initialization = true