# Application name
spring.application.name=YEOGINAMGIM-BACKEND

# Import secret properties if exists
spring.config.import=optional:application-secret.properties

# Server port
server.port=8080

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true